# use Ganache's forked mainnet mode as the default network
# NOTE: You don't *have* to do this, but it is often helpful for testing
networks:
  default: mainnet-fork

# automatically fetch contract sources from Etherscan
autofetch_sources: True

# require OpenZepplin Contracts
dependencies:
  - yearn/yearn-vaults@0.4.4
  - OpenZeppelin/openzeppelin-contracts@4.7.3

# path remapping to support imports from GitHub/NPM
compiler:
  solc:
    version: 0.8.15
    remappings:
      - "@yearnvaults=yearn/yearn-vaults@0.4.4-rc-1"
      - "@openzeppelin=OpenZeppelin/openzeppelin-contracts@4.7.3"

reports:
  exclude_contracts:

